#define SPLIT_USB_DETECT

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE



//#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX
// or
#define UNICODE_SELECTED_MODES UNICODE_MODE_WINCOMPOSE

#define TAPPING_TOGGLE 2