LTO_ENABLE = yes

CONSOLE_ENABLE = no
MOUSEKEY_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

UNICODE_COMMON = yes
UNICODEMAP_ENABLE = yes

AUTO_SHIFT_ENABLE = yes
REPEAT_KEY_ENABLE = yes
COMBO_ENABLE = yes